apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-onlinestore-api-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookreview-onlinestore-api
  template:
    metadata:
      labels:
        app: bookreview-onlinestore-api        
    spec:
      containers:
      - name: bookreview-onlinestore-api
        image: microservicesaks.azurecr.io/bookreview-onlinestore-api:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".05"
            memory: "64M"
          limits:
            cpu: ".1"
            memory: "128M"            
        ports:
        - containerPort: 80
        env:
          - name: DB_CONNECTION
            valueFrom:
              configMapKeyRef:
                name: bookreview-onlinestore-cmp
                key: DB_CONNECTION
      imagePullSecrets:
        - name: microservicesaks-acr-sec    
