kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookreview-category-db-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: bookreview-sto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi