apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookreview-reviewcomment-db-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookreview-reviewcomment-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bookreview-reviewcomment-db
        image: microservicesaks.azurecr.io/microsoft/mssql
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".2"
            memory: "600M"
          limits:
            cpu: ".3"
            memory: "700M"         
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookreview-reviewcomment-db-sec
              key: SA_PASSWORD 
        volumeMounts:
        - name: bookreview-reviewcomment-db-vol
          mountPath: /var/opt/mssql
      volumes:
      - name: bookreview-reviewcomment-db-vol
        persistentVolumeClaim:
          claimName: bookreview-reviewcomment-db-pvc
      imagePullSecrets:
        - name: microservicesaks-acr-sec